### ISSUE TITLE
ImportError: No module named compyte.array

### ISSUE THREAD

**Issue by peter73421** [pyopencl/pyopencl#142]
I just installed pyopencl from github and trying to import pyopencl in python 2.
7.11, I got error as:

Python 2.7.11 (default, Aug 29 2016, 05:24:58)
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyopencl-2016.2-py2.7-linux-aarch64.egg                                                                           /pyopencl/__init__.py", line 34, in <module>
    import pyopencl.cffi_cl as _cl
  File "/usr/lib/python2.7/site-packages/pyopencl-2016.2-py2.7-linux-aarch64.egg                                                                           /pyopencl/cffi_cl.py", line 40, in <module>
    from .compyte.array import f_contiguous_strides, c_contiguous_strides
ImportError: No module named compyte.array
>>> ImportError: No module named compyte.array

can you help me what issue might be?
Thanks

**Comment by inducer** [comment]
These tarballs are broken. Get the release from PyPI:

https://pypi.org/project/pyopencl/

They shouldn't be there. I've asked Github to turn them off, without success.
