### ISSUE TITLE
ImportError: No module named compyte.array

### ISSUE THREAD

**Issue by peter73421** [pyopencl/pyopencl#143]
Hello,

after installation of pyopencl I got this in my python console and not able to import pyopncl

>>> import pyopencl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyopencl-2016.2-py2.7-linux-aarch64.egg                                                                                                                     /pyopencl/__init__.py", line 34, in <module>
    import pyopencl.cffi_cl as _cl
  File "/usr/lib/python2.7/site-packages/pyopencl-2016.2-py2.7-linux-aarch64.egg                                                                                                                     /pyopencl/cffi_cl.py", line 40, in <module>
    from .compyte.array import f_contiguous_strides, c_contiguous_strides
ImportError: No module named compyte.array

**Comment by inducer** [comment]
See #142.

**Comment by inducer** [comment]
Also--wait? Why report the same issue twice?
