### ISSUE TITLE
building on ubuntu python 3.4 makes the 2.7 version

### ISSUE THREAD

**Issue by ImmanuelSamuel** [pyopencl/pyopencl#88]
Hi I am trying to build pyopencl on ubuntu with anaconda python 3.4 64bit. But I end up with warnings saying deprecated numpy api.

```
>>> import pyopencl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/immanuel/programs/pyopencl-2015.1/pyopencl/__init__.py", line 222
    except _cl.RuntimeError, e:
                           ^
SyntaxError: invalid syntax
```

Seems like I am building a 2.7 version

Installation procedure:
```
tar zxvf AMD-APP-SDK-v2.8.1.0-lnx64.tgz
chmod +x Install-AMD-APP.sh
./Install-AMD-APP.sh
tar zxvf icd-registration.tgz
sudo cp -r etc/OpenCL/* /etc/OpenCL/
rm -r etc

sudo apt-get install python-numpy libboost1.55-all-dev python-setuptools

wget http://pypi.python.org/packages/source/p/pyopencl/pyopencl-2011.2.tar.gz
tar xfz pyopencl-2015.1.tar.gz
cd pyopencl-2015.1/
sudo python configure.py                            \
   --boost-inc-dir=/usr/include/boost          \
   --boost-lib-dir=/usr/lib                    \
   --no-use-shipped-boost                      \
   --boost-python-libname=boost_python-py34 \
   --cl-inc-dir=/opt/AMDAPP/include/           \
   --cl-lib-dir=/opt/AMDAPP/lib/x86_64         \
   --cl-libname=OpenCL
make
sudo make install
```

**Comment by ImmanuelSamuel** [comment]
Just used pip install pyopencl it worked like a charm
