### ISSUE TITLE
Calling set_args followed by enqueue_nd_range_kernel raises INVALID_KERNEL_ARGS exception 

### ISSUE THREAD

**Issue by bsdz** [pyopencl/pyopencl#92]
One receives an INVALID_KERNEL_ARGS exception when trying to split a kernel \__call__ into separate set_arg(s) and enqueue_nd_range_kernel methods. This occurs on Windows 10 and Linux using OpenCL 1.1/1.2 Nvidia/Intel on PyOpenCL versions 2014.1, 2015.1 and current master.

Specifically, the following code (adapted from main example).

```python
import numpy as np
import pyopencl as cl

a_np = np.random.rand(50000).astype(np.float32)
b_np = np.random.rand(50000).astype(np.float32)

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

mf = cl.mem_flags
a_g = cl.Buffer(ctx, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=a_np)
b_g = cl.Buffer(ctx, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=b_np)

prg = cl.Program(ctx, """
__kernel void sum(__global const float *a_g, __global const float *b_g, __global float *res_g) {
  int gid = get_global_id(0);
  res_g[gid] = a_g[gid] + b_g[gid];
}
""").build()

res_g = cl.Buffer(ctx, mf.WRITE_ONLY, a_np.nbytes)

#prg.sum(queue, a_np.shape, None, a_g, b_g, res_g)
prg.sum.set_arg(0, a_g)
prg.sum.set_arg(1, b_g)
prg.sum.set_arg(2, res_g)
#prg.sum.set_args(a_g, b_g, res_g)
ev = cl.enqueue_nd_range_kernel(queue, prg.sum, a_np.shape, None)
ev.wait()

res_np = np.empty_like(a_np)
cl.enqueue_copy(queue, res_np, res_g)

# Check on CPU with Numpy:
print(res_np - (a_np + b_np))
print(np.linalg.norm(res_np - (a_np + b_np)))
```

gives the following error

```
Traceback (most recent call last):
  File "C:\..\Scratch\opencl.py", line 28, in <module>
    ev = cl.enqueue_nd_range_kernel(queue, prg.sum, a_np.shape, None)
  File "D:\..l\pyo\lib\site-packages\pyopencl-2015.1-py3.4-win-amd64.egg\pyopencl\cffi_cl.py", line 1197, in enqueue_nd_range_kernel
    global_work_size, local_work_size, c_wait_for, num_wait_for))
  File "D:\..\pyo\lib\site-packages\pyopencl-2015.1-py3.4-win-amd64.egg\pyopencl\cffi_cl.py", line 549, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clenqueuendrangekernel failed: INVALID_KERNEL_ARGS
```

Please see this [thread](http://lists.tiker.net/pipermail/pyopencl/2015-October/002000.html) for more information.

**Comment by inducer** [comment]
```
  knl = prg.sum
  knl.set_arg(0, a_g)
  knl.set_arg(1, b_g)
  knl.set_arg(2, res_g)
  knl.set_args(a_g, b_g, res_g)
  ev = cl.enqueue_nd_range_kernel(queue, knl, a_np.shape, None)
```

**Comment by bsdz** [comment]
It's not entirely clear why one has to assign the kernel to an unclassed variable.

Perhaps add this to the documentation and also add as an example?

**Comment by inducer** [comment]
How about this?

http://documen.tician.de/pyopencl/runtime.html#pyopencl.Program.kernel_name

**Comment by bsdz** [comment]
That looks good to me :+1:
